crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce/', include('ecommerce.urls')),  # Substitua 'meuapp' pelo nome real da sua aplicação
]

ecommerce/urls.py
from django.urls import path
from .views import (
    ProdutoListView,
    ProdutoCreateView,
    ProdutoDetailView,
    ProdutoUpdateView,
    ProdutoDeleteView,
)

urlpatterns = [
    path('', ProdutoListView.as_view(), name='produto_list'),
    path('criar_produto/', ProdutoCreateView.as_view(), name='produto_create'),
    path('detalhe_produto/<int:pk>/', ProdutoDetailView.as_view(), name='produto_detail'),
    path('editar_produto/<int:pk>/', ProdutoUpdateView.as_view(), name='produto_update'),
    path('deletar_produto/<int:pk>/', ProdutoDeleteView.as_view(), name='produto_delete'),
]

ecommerce/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome

ecommerce/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'descricao', 'preco']

ecommerce/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Produto

class ProdutoListView(ListView):
    model = Produto
    template_name = 'produto_list.html'
    context_object_name = 'produtos'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Produto.objects.filter(nome__icontains=query)
        return Produto.objects.all()

class ProdutoCreateView(UserPassesTestMixin, CreateView):
    model = Produto
    template_name = 'produto_form.html'
    fields = ['nome', 'descricao', 'preco']
    success_url = '/ecommerce/'
    
    def test_func(self):
        return self.request.user.is_superuser

class ProdutoDetailView(DetailView):
    model = Produto
    template_name = 'produto_detail.html'
    context_object_name = 'produto'

class ProdutoUpdateView(UserPassesTestMixin, UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    fields = ['nome', 'descricao', 'preco']
    success_url = reverse_lazy('produto_list')

    def test_func(self):
        return self.request.user.is_superuser

class ProdutoDeleteView(UserPassesTestMixin, DeleteView):
    model = Produto
    template_name = 'produto_confirm_delete.html'
    success_url = reverse_lazy('produto_list')

    def test_func(self):
        return self.request.user.is_superuser









    

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meu E-commerce</title>
    <style>
        /* Estilos globais */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 15px;
            text-align: center;
        }
        nav ul {
            list-style: none;
            padding: 0;
            text-align: center;
        }
        nav ul li {
            display: inline-block;
            margin-right: 20px;
        }
        main {
            padding: 20px;
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <div class="logo">
            <h1>Meu E-commerce</h1>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'produto_list' %}">Produtos</a></li>
                <!-- Verificar se o usuário é um superusuário -->
                {% if user.is_superuser %}
                    <li><a href="{% url 'produto_create' %}">Cadastrar Produtos</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Meu E-commerce</p>
    </footer>
</body>
</html>

ecommerce/templates/login.html
<!-- nome_do_template_login.html -->
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <label for="username">Usuário:</label>
        <input type="text" name="username" required>
        <br>
        <label for="password">Senha:</label>
        <input type="password" name="password" required>
        <br>
        <button type="submit">Entrar</button>
    </form>
</body>
</html>
{% endblock %}

ecommerce/templates/produto_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Confirmar Exclusão</h1>
    <p>Tem certeza que deseja excluir o produto "{{ produto.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
    </form>
{% endblock %}

ecommerce/templates/produto_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="produto-detail">
        <h1>Detalhes do Produto: {{ produto.nome }}</h1>
        <img src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
        <p>Descrição: {{ produto.descricao }}</p>
        <p>Preço: R$ {{ produto.preco }}</p>

        <!-- Verificar se o usuário é um superusuário -->
        {% if request.user.is_superuser %}
            <a href="{% url 'produto_update' produto.pk %}">Editar</a>
            <a href="{% url 'produto_delete' produto.pk %}">Excluir</a>
        {% endif %}
    </div>
{% endblock %}

ecommerce/templates/produto_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Adicionar Produto</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nome">Nome:</label>
            {{ form.nome }}
        </div>
        <div class="form-group">
            <label for="id_descricao">Descrição:</label>
            {{ form.descricao }}
        </div>
        <div class="form-group">
            <label for="id_preco">Preço:</label>
            {{ form.preco }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

ecommerce/templates/produto_list.html
{% extends 'base.html' %}

{% block content %}
    <style>
        /* CSS para estilizar a lista de produtos */
        .produtos {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .search-form {
            margin-bottom: 20px;
        }

        .search-input {
            padding: 8px;
            width: 70%;
            margin-right: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
        }

        .search-button {
            padding: 8px 15px;
            border: none;
            border-radius: 4px;
            background-color: #007bff;
            color: white;
            cursor: pointer;
        }

        .produto-list {
            list-style: none;
            padding: 0;
        }

        .produto-item {
            display: inline-block;
            margin-bottom: 20px;
        }

        .produto-link {
            text-decoration: none;
            color: inherit;
        }

        .produto-card {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 10px;
            text-align: center;
            transition: box-shadow 0.3s ease;
        }

        .produto-card:hover {
            box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.2);
        }

        .produto-imagem {
            max-width: 100%;
            height: auto;
            margin-bottom: 10px;
        }

        .produto-nome {
            font-size: 18px;
            margin-bottom: 5px;
        }

        .produto-preco {
            font-size: 16px;
            color: #007bff;
        }
    </style>

    <div class="produtos">
        <h1>Lista de Produtos</h1>
        <form method="GET" class="search-form">
            <input type="text" name="q" placeholder="Buscar por nome do produto" class="search-input">
            <button type="submit" class="search-button">Buscar</button>
        </form>
        <ul class="produto-list">
            {% for produto in produtos %}
                <li class="produto-item">
                    <a href="{% url 'produto_detail' produto.pk %}" class="produto-link">
                        <div class="produto-card">
                            <img src="{{ produto.imagem.url }}" alt="{{ produto.nome }}" class="produto-imagem">
                            <h2 class="produto-nome">{{ produto.nome }}</h2>
                            <p class="produto-preco">Preço: R$ {{ produto.preco }}</p>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}